[project]
name = "arcticicemodel"
version = "0.1.0"
description = "Reduced-order model to simulate annual sea ice growth and melt in the Arctic."
readme = "README.md"
authors = [
    { name = "Caitlin Amos", email = "caitlin.amos@jhuapl.edu" }
]
requires-python = ">=3.12"
dependencies = [
    "cartopy==0.25.0",
    "cftime==1.6.5",
    "cmocean==4.0.3",
    "gsw==3.6.23",
    "ipykernel==7.3.0",
    "matplotlib==3.11.1",
    "netcdf4==1.7.4",
    "numpy==2.5.3",
    "pandas==3.0.5",
    "pytest==9.1.1",
    "pyyaml==6.0.3",
    "scipy==1.18.1",
    "xarray==2026.7.0",
]

[project.scripts]
arcticicemodel = "arcticicemodel:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel] 
packages = ["src/arctic_ice"]